// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCKwzLPR8Q4XzDD8-xxs25TWTBgFBcoHE',
    appId: '1:1055858300882:web:a811cbaf2c9418113cda0b',
    messagingSenderId: '1055858300882',
    projectId: 'gajinn-ef3d3',
    authDomain: 'gajinn-ef3d3.firebaseapp.com',
    storageBucket: 'gajinn-ef3d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKaLqVu_S8kVblK2cFoMkrgGPc3hNpidY',
    appId: '1:1055858300882:android:f76c51396bdffb8e3cda0b',
    messagingSenderId: '1055858300882',
    projectId: 'gajinn-ef3d3',
    storageBucket: 'gajinn-ef3d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9I5LM5p55V7rQRHxw2AnYiuwAqtRhZA',
    appId: '1:1055858300882:ios:474397305fced8603cda0b',
    messagingSenderId: '1055858300882',
    projectId: 'gajinn-ef3d3',
    storageBucket: 'gajinn-ef3d3.appspot.com',
    iosClientId: '1055858300882-lmot6kci8u8ftb016e8vlac1r8puvgfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaj',
  );
}
